config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: %i[index show] do
    resource :upgrade, only: %i[update destroy]
  end

  resources :courses do
    resources :students, only: %i[index create]
    resources :lectures, except: :index
    resources :tasks, except: :index do
      resources :solutions, controller: :task_solutions, only: %i[index create]
    end
  end

  resources :categories
  resources :solutions, only: %i[show edit update destroy]
  resources :upgrades, only: :create

  root 'pages#home'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  expose(:courses) { policy_scope Course.all }
  expose_decorated(:course)
  expose(:category) { course.category }
  expose(:lectures) { policy_scope course.lectures }
  expose_decorated(:tasks) { policy_scope course.tasks }
  expose(:student_solutions) { course.solutions.for_student(current_user) }

  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :authorize_course

  def create
    course.teacher = current_user
    if course.save
      flash[:success] = t '.success'
      redirect_to course
    else
      render :new
    end
  end

  def update
    if course.update(course_params)
      flash[:success] = t '.success'
      redirect_to course
    else
      render :edit
    end
  end

  def destroy
    course.destroy
    flash[:success] = t '.success'
    redirect_to courses_path
  end

  private

  def course_params
    permitted_attributes(Course)
  end

  def authorize_course
    authorize course
  end
end

app/views/courses/_course.html.haml
%li= link_to course.name, course

app/views/courses/_form.html.haml
= simple_form_for course do |f|
  = f.error_notification

  = f.association :category, prompt: :translate
  = f.input :name
  = f.input :desc

  = f.button :submit

app/views/courses/edit.html.haml
- content_for :sidebar do
  - if policy(course).destroy?
    .delete= link_to t('.delete'), course, method: :delete

- breadcrumb course

.page-header
  %h1= t '.title'

= render 'form'

app/views/courses/index.html.haml
- content_for :sidebar do
  - if policy(Category).index?
    .categories= link_to t('.categories'), categories_path

- breadcrumb :courses

.page-header
  %h1= t '.title'

%ul= render courses

app/views/courses/new.html.haml
- breadcrumb :new_course

.page-header
  %h1= t '.title'

= render 'form'

app/views/courses/show.html.haml
- content_for :sidebar do
  - if policy(category).show?
    .category= link_to category.name, category

  - if policy(course).edit?
    .edit= link_to t(:edit), [:edit, course]

  - if policy(course).enroll?
    .enroll= button_to t('.enroll'), [course, :students]

  - if policy(course).list_students?
    .students= link_to t('.students'), [course, :students]

  - if policy(Lecture.new(course: course)).new?
    .new= link_to t('.add_lecture'), [:new, course, :lecture]

  - if policy(Task.new(course: course)).new?
    .new= link_to t('.add_task'), [:new, course, :task]

  - if course.studied_by? current_user
    .score
      = bs_panel t('.your_score') do
        = course.score_for(current_user)

- breadcrumb course

.page-header
  %h1= course.name

.teacher
  %i= link_to_if policy(course.teacher).show?, course.teacher.name, course.teacher

.description= course.description_formatted

- if policy(course).list_lectures?
  #lectures
    = bs_panel_list t('.lectures') do
      = render lectures

- if policy(course).list_tasks?
  #tasks
    = bs_panel_list t('.tasks') do
      = render tasks

app/views/courses/students.html.haml
.row
  .col-md-3
    = link_to course, class: 'btn btn-default' do
      = icon 'arrow-left', 'Wróć'

  .col-md-9
    %h1= course.name
    %h2 Zapisani studenci
    %ul.students= render course.students