config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: %i[index show] do
    resource :upgrade, only: %i[update destroy]
  end

  resources :courses do
    resources :students, only: %i[index create]
    resources :lectures, except: :index
    resources :tasks, except: :index do
      resources :solutions, controller: :task_solutions, only: %i[index create]
    end
  end

  resources :categories
  resources :solutions, only: %i[show edit update destroy]
  resources :upgrades, only: :create

  root 'pages#home'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id   :integer          not null, primary key
#  name :string
#

class Category < ApplicationRecord
  has_many :courses, dependent: :destroy

  validates :name,
            presence: true,
            uniqueness: true,
            length: { in: 3..100 }

  def to_param
    "#{id}-#{name}".parameterize
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  expose_decorated(:categories) { policy_scope Category.all }
  expose(:category)

  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :authorize_category

  def create
    if category.save
      flash[:success] = t '.success'
      redirect_to category
    else
      render :new
    end
  end

  def update
    if category.update(category_params)
      flash[:success] = t '.success'
      redirect_to category
    else
      render :edit
    end
  end

  def destroy
    category.destroy
    flash[:success] = t '.success'
    redirect_to categories_path
  end

  private

  def category_params
    permitted_attributes(Category)
  end

  def authorize_category
    authorize category
  end
end

app/views/categories/_category.html.haml
%li
  = link_to category.name, category
  = category.courses_count_formatted

app/views/categories/_form.html.haml
= simple_form_for category do |f|
  = f.error_notification

  = f.input :name, autofocus: true

  = f.button :submit

app/views/categories/edit.html.haml
- breadcrumb category

.page-header
  %h1= t '.title'

= render 'form'

app/views/categories/index.html.haml
- breadcrumb :categories

.page-header
  %h1= t '.title'

- if policy(Category).new?
  .new= link_to t('.add_category'), new_category_path

%ul= render categories

app/views/categories/new.html.haml
- breadcrumb :categories

.page-header
  %h1= t '.title'

= render 'form'

app/views/categories/show.html.haml
- breadcrumb category

.page-header
  %h1= category.name

- if policy(category).edit?
  .edit= link_to t(:edit), [:edit, category]

- if policy(category).destroy?
  .delete= link_to t(:delete), category, method: :delete

%ul= render category.courses