config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: %i[index show] do
    resource :upgrade, only: %i[update destroy]
  end

  resources :courses do
    resources :students, only: %i[index create]
    resources :lectures, except: :index
    resources :tasks, except: :index do
      resources :solutions, controller: :task_solutions, only: %i[index create]
    end
  end

  resources :categories
  resources :solutions, only: %i[show edit update destroy]
  resources :upgrades, only: :create

  root 'pages#home'

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{alert_name(name.to_sym)}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to root_path, id: 'logo', class: 'navbar-brand' do
      = icon 'fas', 'graduation-cap', t(:app_name)
    %ul.nav.navbar-nav.navbar-right
      %li= link_to t('courses.index.title'), courses_path
      - if signed_in?
        %li= link_to t(:my_courses), root_path
        %li.dropdown
          %a.dropdown-toggle{ href: '#', data: { toggle: 'dropdown' } }
            = current_user.name
            %i.caret
          %ul.dropdown-menu
            %li
              = link_to current_user do
                = icon 'fas', 'user', t(:my_profile)
            %li
              = link_to edit_user_registration_path do
                = icon 'fas', 'cogs', t(:settings)
            %li.divider
            %li
              = link_to destroy_user_session_path, method: :delete do
                = icon 'fas', 'sign-out-alt', t(:sign_out)
      - else
        %li= link_to t(:sign_in), new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= t(:app_name)
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      = render 'layouts/flash_messages'
      .row
        .col-md-3#sidebar
          = yield :sidebar
        .col-md-9
          = breadcrumbs style: :bootstrap, link_current: true, link_current_to_request_path: false
          = yield
      -# .debug= debug(params) if Rails.env.development?